# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
# site_title: "StudioRich | Lo-Fi Experiences"
email: "hello@studiorich.shop"
description: "StudioRich (Studio Rich) blends lo-fi music, urban visuals, and collectible NFT drops. Discover the upcoming StudioRich Player — a desktop portal for rhythm and story."
baseurl: ""
url: "https://studiorich.shop"
twitter_username: "studiorxch"
github_username: "studiorxch"
repository: studiorxch/home

blog_subtitles:
  - "Sound + Visual Culture in Loops"
  - "Where Lo-Fi Lives, Breathes, and Crosses Formats"
  - "Archives of Lo-Fi Memory, Weird Internet, and Beat Culture"
  - "Filed Under: Loops, Pixels, and Subcultures"
  - "Lo-Fi Soundscapes and Visual Beat Loop Aesthetics"

collections:
  desktop:
    output: false

  events:
    output: true
    permalink: /events/:slug/

  future: true # so future-dated events appear in dev

  files:
    output: false

  playground:
    output: true
    permalink: /playground/:name/

  tracks: # Music Library
    output: true
    permalink: /tracks/:name/

  shop: # Shop
    output: true
    permalink: /shop/:title/
  redirects:
    output: true

# Ensure future-dated items build (for Upcoming)

defaults:
  - scope:
      path: "_events"
      type: events
    values:
      layout: event
      sitemap: true
      last_modified_at: 2025-06-12

include:
  - /assets/ui

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-read-file

sass:
  sass_dir: _sass

timezone: America/New_York

whitelist:
  - jekyll-readme-index
  - jekyll-include-cache
  - jekyll-read-file

# Or if you're on newer Jekyll: (how new is new?)
safe: false

# Exclude unnecessary files from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - _site/
  - events.timeline.json

# Add custom settings as needed
favicon: "/assets/img/logo/favicon.ico" # Make sure to upload your favicon if you want one

# Google Analytics (optional, add only if you have GA setup)
google_analytics: "G-E5KN2YJJKF"

redirect_from:
  json: false
