name: Printful Sync
on:
  schedule: [{ cron: "0 6 * * *" }] # 6:00 UTC daily
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }

      # fetch Printful data into _data and assets/data
      - run: |
          mkdir -p _data assets/data
          curl -s "https://studiorich-api.vercel.app/api/printful/products" \
            | tee _data/printful.json > assets/data/printful.json

      # ⬇️ add the shop meta step right after
      - name: Write shop meta
        run: |
          TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          COUNT=$(jq 'length' _data/printful.json || echo 0)
          echo "{\"updated_at\":\"$TS\",\"count\":$COUNT}" > _data/shop_meta.json

      # generate static product pages (optional step we had before)
      - name: Generate static product pages
        run: |
          mkdir -p _shop
          jq -c '.[]' _data/printful.json | while read -r row; do
            id=$(echo "$row" | jq -r '.id')
            name=$(echo "$row" | jq -r '.name // .sync_product.name // "Untitled"')
            thumb=$(echo "$row" | jq -r '.thumbnail_url // .thumbnail // .sync_product.thumbnail // empty')
            cat > "_shop/${id}.md" <<EOF
---
layout: product
title: "${name//\"/\\\"}"
permalink: /shop/${id}/
product_id: ${id}
thumbnail: "${thumb}"
---
EOF
          done

      - name: Commit
        run: |
          git config user.name "printful-bot"
          git config user.email "printful-bot@users.noreply.github.com"
          git add _data/printful.json assets/data/printful.json _data/shop_meta.json _shop/*.md
          git commit -m "chore: nightly Printful sync" || echo "No changes"
          git push
