name: Printful Sync
on:
  schedule: [{ cron: "0 6 * * *" }] # 6:00 UTC daily
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm i node-fetch@3
      - env:
          PRINTFUL_KEY: ${{ secrets.PRINTFUL_KEY }}
        run: |
          node -e '
            import fetch from "node-fetch";
            const hdr={headers:{Authorization:`Bearer ${process.env.PRINTFUL_KEY}`}};
            const url="https://api.printful.com/store/products";
            const fs=(await import("fs")).default;
            const data=await (await fetch(url,hdr)).json();
            fs.mkdirSync("assets/data",{recursive:true});
            fs.writeFileSync("assets/data/printful.json", JSON.stringify(data.result,null,2));
          '
      - name: Commit
        run: |
          git config user.name "printful-bot"
          git config user.email "printful-bot@users.noreply.github.com"
          git add assets/data/printful.json
          git commit -m "chore: nightly Printful sync" || echo "No changes"
          git push


          # in .github/workflows/printful-sync.yml
          # replace assets/data with _data
          fs.mkdirSync("_data",
          {recursive: true
          });
          fs.writeFileSync("_data/printful.json", JSON.stringify(data.result,
          null,
          2));
